# -*- coding: utf-8 -*-
"""MatrixTranspose.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jF_mJ238MJRgovtZk7ASjcyMEmPW1tLb
"""

#program to find transpose of a matrix using list.

r=int(input("enter the number of rows"))
c=int(input("enter the number of columns"))
matrix=[]
re=[]
a=[]
k=[]

print("enter the matrix:\n")
for i in range(r):
  for j in range(c):
    a.append(int(input()))
    matrix.append(a)

print("The matrix is:\n")
for i in range(r):
    for j in range(c):
        print(matrix[i][j],end = " ")
    print()

print("the transpose is\n")
for i in range(r):
  for j in range(c):
    re=matrix[i][j]
    k.append(re)

for y in k:
   print(y)