# -*- coding: utf-8 -*-
"""matrixAddition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-rvrIlJ6I9wmtMD8TBu3zmyfoCy5knN
"""

# program to add two matrices using list.

r=int(input("enter the number of rows"))
c=int(input("enter the number of columns"))
matrix1=[]
matrix2=[]
a=[]
b=[]
sum=[]
print("enter the first matrix:\n")
for i in range(r):
  for j in range(c):
    a.append(int(input()))
    matrix1.append(a)

print("enter the second matrix:\n")
for i in range(r):
  for j in range(c):
    b.append(int(input()))
    matrix2.append(b)

print("The first matrix is:\n")
for i in range(r):
    for j in range(c):
        print(matrix1[i][j],end = " ")
    print()

print("The second matrix is:\n")
for i in range(r):
    for j in range(c):
        print(matrix2[i][j],end = " ")
    print()
s=[]
print("The sum is:\n ")
for i in range(r):
  for j in range(c):
    s=matrix1[i][j]+matrix2[i][j]
    sum.append(s)

for r in sum:
    print(r)